# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    env_file:
      - .env
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - influxdbnetwork
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - influxdbnetwork

volumes:
  influxdb2-data:
  influxdb2-config:
  mongodata:

networks:
  influxdbnetwork:
