# compose.yaml
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork

volumes:
  mongodata:

networks:
  dbnetwork:
